apiVersion: v1
kind: Pod
metadata:
  name: debug-aws-sso
  namespace: argocd
spec:
  containers:
  - name: debug
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: secret-aws-sso-creds
      mountPath: /secrets
      readOnly: true
  volumes:
  - name: secret-aws-sso-creds
    secret:
      secretName: aws-sso-creds
#