apiVersion: v1
kind: Pod
metadata:
  name: aws-debug
  namespace: argocd
spec:
  restartPolicy: Never
  containers:
    - name: aws-cli
      image: amazon/aws-cli:2.14.6  # Official AWS CLI v2 image
      command: ["sleep", "3600"]
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-sso-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-sso-creds
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-sso-creds
              key: AWS_SESSION_TOKEN
        - name: AWS_DEFAULT_REGION
          value: us-west-2

# k exec -it aws-debug -n argocd -- bash