apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-dag-cron
  namespace: default
spec:
  schedule: "* 12 * * *"  # every minute
  concurrencyPolicy: "Allow"
  startingDeadlineSeconds: 5
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  workflowSpec:
    serviceAccountName: argo-workflow-sa
    entrypoint: hello-dag
    templates:
      - name: hello-dag
        dag:
          tasks:
            - name: hello
              template: print-hello
            - name: world
              template: print-world
              dependencies: ["hello"]
            - name: goodbye
              template: print-goodbye
              dependencies: ["hello"]
            - name: wait
              template: wait
              dependencies: ["world", "goodbye"]

      - name: print-hello
        container:
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "hello $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
              sleep 2

      - name: print-world
        container:
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "world $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
              sleep 2

      - name: print-goodbye
        container:
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "goodbye $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
              sleep 2

      - name: wait
        container:
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting 10 seconds..."
              sleep 10