apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-dag-cron
  namespace: default
spec:
  schedule: "* * * * *"  # every minute
  concurrencyPolicy: "Allow"
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  workflowSpec:
    entrypoint: hello-dag
    templates:
      - name: hello-dag
        dag:
          tasks:
            - name: hello
              template: print-hello
            - name: world
              template: print-world
              depends: hello
            - name: goodbye
              template: print-goodbye
              depends: hello
            - name: wait
              template: wait
              depends: [world, goodbye]

      - name: print-hello
        container:
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["echo hello $(date -u +'%Y-%m-%dT%H:%M:%SZ'); sleep 30"]

      - name: print-world
        container:
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["echo world $(date -u +'%Y-%m-%dT%H:%M:%SZ'); sleep 30"]

      - name: print-goodbye
        container:
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["echo goodbye $(date -u +'%Y-%m-%dT%H:%M:%SZ'); sleep 30"]

      - name: wait
        container:
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["echo Waiting 2 hours...; sleep 7200"]
