---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensor-sa
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: sensor-sa
    namespace: argocd
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io