apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: aws-sqs
  namespace: argocd
spec:
  sqs:
    example:
      region: us-west-2
      queue: dat-argo-wf-hello-pr-12-events
      jsonBody: true
      waitTimeSeconds: 20
      # access/secret keys from secret
      accessKey:
        key: accesskey
        name: aws-secret
      secretKey:
        key: secretkey
        name: aws-secret
      # temporary session token via environment variable
      env:
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: sessiontoken
