apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: aws-sqs
  namespace: argocd
spec:
  sqs:
    example:
      region: us-west-2
      queue: dat-argo-wf-hello-pr-12-events
      jsonBody: true
      waitTimeSeconds: 20
      # access/secret keys from secret
      accessKey:
        key: AWS_ACCESS_KEY_ID
        name: aws-sso-creds
      secretKey:
        key: AWS_SECRET_ACCESS_KEY
        name: aws-sso-creds
      # temporary session token via environment variable
      sessionToken:
        name: aws-sso-creds
        key: AWS_SESSION_TOKEN
