apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: aws-sqs
  namespace: argocd
spec:
  service:
    ports:
      - port: 7777
        targetPort: 7777
  sqs:
    example:
      queue: dat-argo-wf-hello-pr-12-events
      region: us-west-2  # or read from secret
      accessKey:
        name: aws-sso-creds
        key: AWS_ACCESS_KEY_ID
      secretKey:
        name: aws-sso-creds
        key: AWS_SECRET_ACCESS_KEY
      sessionToken:
        name: aws-sso-creds
        key: AWS_SESSION_TOKEN
      sqsPollingWaitTimeSeconds: 20
      jsonBody: true
  template:
    spec:
      containers:
        - name: main
          image: quay.io/argoproj/argo-events:v1.9.6
          args:
            - eventsource
            - --config
            - /etc/eventsource/config
          volumeMounts:
            - name: secret-aws-sso-creds
              mountPath: /argo-events/secrets/aws-sso-creds
              readOnly: true
      volumes:
        - name: secret-aws-sso-creds
          secret:
            secretName: aws-sso-creds
