apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: sqs-es
  namespace: argocd
spec:
  sqs:
    myqueue:
      region: us-west-2
      queue: "https://sq.us-west-2.amazonaws.com/654654598303/dat-argo-wf-hello-pr-12-events"
      waitTimeSeconds: 5
      jsonBody: true
      deleteMessage: true
      visibilityTimeoutSeconds: 30
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-sso-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-sso-creds
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-sso-creds
              key: AWS_SESSION_TOKEN
