apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sqs-sensor
  namespace: argocd
spec:
  dependencies:
    - name: sqs-event
      eventSourceName: sqs-es
      eventName: myqueue

  triggers:
    - template:
        name: run-hello
        k8s:
          group: ""
          version: v1
          resource: pods
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: hello-from-sqs-
                namespace: default
              spec:
                restartPolicy: Never
                containers:
                  - name: hello
                    image: busybox
                    command: ["/bin/sh", "-c"]
                    args:
                      - |
                        echo "Hello from SQS!"
                        echo "Message payload:"
                        echo "{{ .Input.body }}"
                        sleep 10
